% This script is for extracting spots statistics from TrackMate trajectory
% saved as 'csv' files

function Read_TrackMate_traj_spots_csv

disp('Please select the trajectory spots statistics csv files generated by TrackMate:');
[filename,path] = uigetfile('multiselect','on','.csv','Select the file to convert');
addpath(path)
cd(path)

if ischar(filename)
    N_file = 1;
else
    N_file = length(filename);
end

for i = 1:N_file
    
    if N_file==1
        disp(filename)
        filename_temp = filename;
    else
        disp(filename{i})
        filename_temp = filename{i};
    end
    
    opts = detectImportOptions(filename_temp);

    Name = opts.SelectedVariableNames;
    Traj_index = find(strcmp(Name,'TRACK_ID')); 
    %'TRACK_ID' in the spots statistics starts from 0 instead of 1, which is 
    %1 smaller than 'x_particle__id' in the trajectory xlsx file, which starts
    %from 1.
    Frame_index = find(strcmp(Name,'FRAME'));
    t_index = find(strcmp(Name,'POSITION_T')); %t_index = Frame_index * time_interval
    x_index = find(strcmp(Name,'POSITION_X'));
    y_index = find(strcmp(Name,'POSITION_Y'));
    z_index = find(strcmp(Name,'POSITION_Z'));
%     MeanInt_index = find(strcmp(Name,'MEAN_INTENSITY'));
%     MaxInt_index = find(strcmp(Name,'MAX_INTENSITY'));
%     TotInt_index = find(strcmp(Name,'TOTAL_INTENSITY'));
    MeanInt_index = find(strcmp(Name,'MEAN_INTENSITY_CH1'));
    MaxInt_index = find(strcmp(Name,'MAX_INTENSITY_CH1'));
    TotInt_index = find(strcmp(Name,'TOTAL_INTENSITY_CH1'));

    total_index = [Traj_index,Frame_index,MeanInt_index,MaxInt_index,TotInt_index,x_index,y_index,z_index,t_index];

    opts.SelectedVariableNames = total_index; %Extract 'Track_ID,Frame,Mean_intensity,Max_intensity,Total_intensity,Position_x,Position_y,Position_Z,Position_T' information
    M_select = readmatrix(filename_temp,opts);

    Trajectory = M_select(:,1)+1; %Trajectory index for particles with trajectories, '+1' is to align with trajctory index identified in xlsx trajectory files
    Frame = M_select(:,2); %Frame index of identified particles with trajectories
    MeanInt = M_select(:,3); %Mean intensity of identified particles
    MaxInt = M_select(:,4); %Maximum intensity of identified particles
    TotInt = M_select(:,5); %Total intensity of identified particles
    x = M_select(:,6); %Particle trajectory x in micron unit, differen from pixel values in Mosaic plugin
    y = M_select(:,7); %Particle trajectory y in micron unit
    z = M_select(:,8); %Particle trajectory z in micron unit
    t = M_select(:,9); %Particle trajectory t in second unit

    N = max(Trajectory); 
    Length = zeros(N,1);
    mean_MeanInt = zeros(N,1);
    mean_MaxInt = zeros(N,1);
    mean_TotInt = zeros(N,1);
    for j = 1:N
        temp_index = (Trajectory == j); %logic index of particle within ith trajectory
        Length(j) = length(find(temp_index));
        mean_MeanInt(j) = mean(MeanInt(temp_index));
        mean_MaxInt(j) = mean(MaxInt(temp_index));
        mean_TotInt(j) = mean(TotInt(temp_index));
    end

    spots = struct( 'N_tracks',N,...
                    'L_tracks',Length,...
                    'Mean_I',mean_MeanInt,...
                    'Max_I',mean_MaxInt,...
                    'Total_I',mean_TotInt);

    saved_name1 = regexprep(filename_temp,'.csv','');
    saved_name = ['spots_',saved_name1];
    save(saved_name,'spots')
    
end

end
